import { SocietyEvent, Ticket, User, Notification, SubOrganizerInvite, ChatMessage, Society, Review } from "./types";

const today = new Date();
function daysFromNow(d: number, h = 17, m = 0) {
  const date = new Date(today);
  date.setDate(date.getDate() + d);
  date.setHours(h, m, 0, 0);
  return date.toISOString();
}

export const seedUsers: User[] = [
  // ---------- Students ----------
  {
    id: "u_mumtaz",
    name: "Mumtaz Ali",
    email: "mumtaz@giki.edu.pk",
    regNumber: "2023591",
    password: "demo123",
    role: "student",
    program: "BS Computer Science",
    avatarSeed: "mumtaz",
    phone: "+92 312 0000001",
    isGikian: true,
  },
  {
    id: "u_haris",
    name: "Muhammad Haris",
    email: "haris@giki.edu.pk",
    regNumber: "2023428",
    password: "demo123",
    role: "student",
    program: "BS Computer Science",
    avatarSeed: "haris",
    phone: "+92 312 0000002",
    isGikian: true,
  },
  {
    id: "u_ahmed",
    name: "Ahmed Raza",
    email: "ahmed@giki.edu.pk",
    regNumber: "2023800",
    password: "demo123",
    role: "student",
    program: "BS Data Science",
    avatarSeed: "ahmed",
    phone: "+92 312 0000004",
    isGikian: true,
  },
  // Example pre-existing non-GIKIAN student (registered for an external-allowed event)
  {
    id: "u_zara",
    name: "Zara Khan",
    email: "zara.khan@nust.edu.pk",
    password: "demo123",
    role: "student",
    avatarSeed: "zara",
    phone: "+92 333 0000099",
    isGikian: false,
    cnic: "13503-1234567-2",
    universityName: "NUST Islamabad",
    emergencyContactName: "Mr. Khan (father)",
    emergencyContact: "+92 333 0000091",
  },

  // ---------- Organizers ----------
  {
    id: "u_ammar",
    name: "Ammar Khan",
    email: "ammar@giki.edu.pk",
    regNumber: "2023378",
    password: "lds2026",
    role: "organizer",
    society: "Literary & Debating Society (LDS)",
    program: "BS Data Science",
    avatarSeed: "ammar",
    phone: "+92 312 0000003",
    isGikian: true,
    accountStatus: "approved",
    approvedAt: daysFromNow(-200, 10),
  },
  {
    id: "u_hamza",
    name: "Hamza Faraz",
    email: "hamza@giki.edu.pk",
    regNumber: "2023802",
    password: "mlsa2026",
    role: "organizer",
    society: "MLSA — Microsoft Learn Student Ambassadors",
    program: "BS Artificial Intelligence",
    avatarSeed: "hamza",
    phone: "+92 312 0000005",
    isGikian: true,
    accountStatus: "approved",
    approvedAt: daysFromNow(-180, 10),
  },
  // A second organizer for LDS demonstrating multiple organizers per society
  {
    id: "u_sania",
    name: "Sania Bilal",
    email: "sania@giki.edu.pk",
    regNumber: "2024112",
    password: "lds2026",
    role: "organizer",
    society: "Literary & Debating Society (LDS)",
    program: "BS Mechanical Engineering",
    avatarSeed: "sania",
    phone: "+92 312 0000006",
    isGikian: true,
    accountStatus: "approved",
    approvedAt: daysFromNow(-60, 10),
  },

  // ---------- Admin (Dean of Student Affairs) ----------
  {
    id: "u_sabir",
    name: "Sabir Ahmed",
    email: "dean.sa@giki.edu.pk",
    password: "dean2026",
    role: "admin",
    avatarSeed: "sabir",
    phone: "+92 938 281 3000",
    isGikian: true,
  },
];

export const seedEvents: SocietyEvent[] = [
  {
    id: "evt_debate",
    title: "Inter-Society Debate Championship",
    description:
      "GIKI's flagship debate event — six societies face off in a single elimination format.",
    longDescription:
      "The annual Inter-Society Debate Championship returns! Six top societies will compete across three rounds of British Parliamentary style debate. Topics will be announced 30 minutes before each round. Refreshments and a panel critique session included. Bring your wit — we'll bring the stage.",
    organizerId: "u_ammar",
    society: "Literary & Debating Society (LDS)",
    category: "Competition",
    date: daysFromNow(3, 17),
    endDate: daysFromNow(3, 21),
    venue: "Main Auditorium",
    capacity: 600,
    ticketPrice: 200,
    coverHue: "260",
    coverEmoji: "🎤",
    status: "approved",
    approvedBy: "u_sabir",
    approvedAt: daysFromNow(-1, 14),
    facultyAdvisor: "Dr. Sumayya Khan",
    budget: 35000,
    resourcesRequested: ["Sound system", "Stage lighting", "Refreshments"],
    createdAt: daysFromNow(-5, 11),
    pocName: "Ammar Khan",
    pocPhone: "+92 312 0000003",
    allowNonGikian: false,
  },
  {
    id: "evt_hackathon",
    title: "Code Vortex — 24h AI Hackathon",
    description:
      "Build a working AI project in 24 hours. Prizes worth 150,000 PKR and recruiter access.",
    longDescription:
      "Code Vortex is MLSA's flagship hackathon. Teams of 2–4 will compete on an AI-themed challenge revealed at kickoff. Mentors from Systems Limited, 10Pearls, and Afiniti will be available throughout. Recruiters will scout teams during demo round.",
    organizerId: "u_hamza",
    society: "MLSA — Microsoft Learn Student Ambassadors",
    category: "Tech",
    date: daysFromNow(8, 9),
    endDate: daysFromNow(9, 9),
    venue: "CS Auditorium",
    capacity: 150,
    ticketPrice: 500,
    coverHue: "200",
    coverEmoji: "💻",
    status: "approved",
    approvedBy: "u_sabir",
    approvedAt: daysFromNow(-2, 10),
    facultyAdvisor: "Dr. Faisal Bukhari",
    budget: 180000,
    resourcesRequested: ["Lab access", "Power outlets", "WiFi boost", "Food x 4 meals"],
    createdAt: daysFromNow(-9, 14),
    pocName: "Hamza Faraz",
    pocPhone: "+92 312 0000005",
    allowNonGikian: true, // open to students from other universities
  },
  {
    id: "evt_seminar",
    title: "From Prompt to Product — Building with LLMs",
    description:
      "A free seminar on shipping production-grade LLM apps. By Engr. Sara Ali (Stripe).",
    longDescription:
      "Engr. Sara Ali (ex-Stripe, currently CTO at Mosaic Labs) will walk through the architecture, prompt patterns, eval strategies, and gotchas of shipping LLM features at scale. Q&A and pizza after.",
    organizerId: "u_hamza",
    society: "MLSA — Microsoft Learn Student Ambassadors",
    category: "Seminar",
    date: daysFromNow(5, 16, 30),
    endDate: daysFromNow(5, 18, 30),
    venue: "Seminar Hall, Incubation Center",
    capacity: 100,
    ticketPrice: 0,
    coverHue: "180",
    coverEmoji: "🧠",
    status: "approved",
    approvedBy: "u_sabir",
    approvedAt: daysFromNow(-3, 11),
    facultyAdvisor: "Dr. Faisal Bukhari",
    budget: 0,
    createdAt: daysFromNow(-7, 16),
    pocName: "Hamza Faraz",
    pocPhone: "+92 312 0000005",
    allowNonGikian: false,
  },
  {
    id: "evt_workshop",
    title: "UI/UX Workshop — Figma to Production",
    description:
      "Hands-on workshop on designing accessible interfaces, prototyping, and dev-handoff.",
    organizerId: "u_ammar",
    society: "Literary & Debating Society (LDS)",
    category: "Workshop",
    date: daysFromNow(11, 14),
    endDate: daysFromNow(11, 18),
    venue: "ACB MLH2",
    capacity: 150,
    ticketPrice: 350,
    coverHue: "320",
    coverEmoji: "🎨",
    status: "pending",
    facultyAdvisor: "Dr. Sumayya Khan",
    budget: 22000,
    resourcesRequested: ["Studio booking", "Projector", "Whiteboards"],
    createdAt: daysFromNow(-1, 10),
    pocName: "Ammar Khan",
    pocPhone: "+92 312 0000003",
    allowNonGikian: false,
    submissionNote: "Would appreciate quick approval — Figma licenses expire in two weeks.",
  },
  {
    id: "evt_cultural",
    title: "Sham-e-Ghazal — Cultural Night",
    description:
      "An evening of Urdu poetry, ghazal, and live qawwali. Bring a friend.",
    organizerId: "u_ammar",
    society: "Literary & Debating Society (LDS)",
    category: "Cultural",
    date: daysFromNow(15, 19),
    endDate: daysFromNow(15, 22),
    venue: "Faculty Club",
    capacity: 600,
    ticketPrice: 150,
    coverHue: "30",
    coverEmoji: "🌙",
    status: "pending",
    facultyAdvisor: "Dr. Sumayya Khan",
    budget: 48000,
    resourcesRequested: ["Stage", "Audio", "Carpets", "Refreshments"],
    createdAt: daysFromNow(0, 10),
    pocName: "Ammar Khan",
    pocPhone: "+92 312 0000003",
    allowNonGikian: true,
  },
  {
    id: "evt_past",
    title: "Freshman Welcome Mixer",
    description:
      "An icebreaker for batch 33. Already happened — included to show 'past events'.",
    organizerId: "u_hamza",
    society: "MLSA — Microsoft Learn Student Ambassadors",
    category: "Cultural",
    date: daysFromNow(-12, 18),
    endDate: daysFromNow(-12, 22),
    venue: "Faculty Lounge",
    capacity: 100,
    ticketPrice: 0,
    coverHue: "100",
    coverEmoji: "🎉",
    status: "completed",
    approvedBy: "u_sabir",
    approvedAt: daysFromNow(-20, 14),
    facultyAdvisor: "Dr. Faisal Bukhari",
    budget: 0,
    createdAt: daysFromNow(-25, 14),
    pocName: "Hamza Faraz",
    pocPhone: "+92 312 0000005",
    allowNonGikian: false,
  },
];

export const seedTickets: Ticket[] = [
  {
    id: "tkt_001",
    eventId: "evt_seminar",
    userId: "u_mumtaz",
    bookedAt: daysFromNow(-2, 14),
    status: "confirmed",
    paymentMethod: "online",
    amount: 0,
    qrPayload: "GIKI-EVENT|evt_seminar|tkt_001|u_mumtaz",
    ticketCode: "MZ7K-1A4P",
    seatLabel: "Open seating",
  },
  {
    id: "tkt_002",
    eventId: "evt_past",
    userId: "u_mumtaz",
    bookedAt: daysFromNow(-15, 10),
    status: "scanned",
    paymentMethod: "online",
    amount: 0,
    scannedAt: daysFromNow(-12, 18, 15),
    scannedBy: "u_hamza",
    qrPayload: "GIKI-EVENT|evt_past|tkt_002|u_mumtaz",
    ticketCode: "PXY9-7QR2",
    seatLabel: "Open seating",
  },
];

export const seedNotifications: Notification[] = [
  {
    id: "n_001",
    userId: "u_mumtaz",
    title: "Welcome to Event Hub",
    body: "You have 1 active ticket and 2 events worth checking out this week.",
    icon: "✨",
    read: false,
    tone: "info",
    createdAt: daysFromNow(0, 9),
  },
  {
    id: "n_002",
    userId: "u_ammar",
    title: "Workshop submission received",
    body: "Your event 'UI/UX Workshop — Figma to Production' is awaiting Dean approval.",
    icon: "📨",
    read: false,
    tone: "info",
    createdAt: daysFromNow(-1, 10, 5),
  },
  {
    id: "n_003",
    userId: "u_sabir",
    title: "2 events awaiting approval",
    body: "Sham-e-Ghazal and UI/UX Workshop need your review.",
    icon: "🔔",
    read: false,
    tone: "warn",
    createdAt: daysFromNow(0, 8),
  },
];

export const seedInvitations: SubOrganizerInvite[] = [];
export const seedChatMessages: ChatMessage[] = [];

// Pre-approved GIKI societies. Multiple organizers can belong to the same society.
export const seedSocieties: Society[] = [
  {
    id: "soc_lds",
    name: "Literary & Debating Society (LDS)",
    status: "approved",
    approvedBy: "u_sabir",
    approvedAt: daysFromNow(-365, 10),
    createdAt: daysFromNow(-365, 10),
    description: "GIKI's flagship literary and debating society.",
  },
  {
    id: "soc_mlsa",
    name: "MLSA — Microsoft Learn Student Ambassadors",
    status: "approved",
    approvedBy: "u_sabir",
    approvedAt: daysFromNow(-300, 10),
    createdAt: daysFromNow(-300, 10),
    description: "Tech community building Microsoft-powered initiatives.",
  },
  {
    id: "soc_iet",
    name: "IET — Institution of Engineering and Technology",
    status: "approved",
    approvedBy: "u_sabir",
    approvedAt: daysFromNow(-280, 10),
    createdAt: daysFromNow(-280, 10),
  },
  {
    id: "soc_pls",
    name: "Photographic & Literary Society (PLS)",
    status: "approved",
    approvedBy: "u_sabir",
    approvedAt: daysFromNow(-250, 10),
    createdAt: daysFromNow(-250, 10),
  },
  {
    id: "soc_giki_sports",
    name: "GIKI Sports Society",
    status: "approved",
    approvedBy: "u_sabir",
    approvedAt: daysFromNow(-200, 10),
    createdAt: daysFromNow(-200, 10),
  },
  {
    id: "soc_aces",
    name: "ACES — ACM-GIKI",
    status: "approved",
    approvedBy: "u_sabir",
    approvedAt: daysFromNow(-180, 10),
    createdAt: daysFromNow(-180, 10),
  },
  {
    id: "soc_rcs",
    name: "Resource Conservation Society (RCS)",
    status: "approved",
    approvedBy: "u_sabir",
    approvedAt: daysFromNow(-150, 10),
    createdAt: daysFromNow(-150, 10),
  },
];

export const seedReviews: Review[] = [
  {
    id: "rev_001",
    eventId: "evt_past",
    userId: "u_mumtaz",
    rating: 5,
    body: "Loved the mixer! Met a bunch of new people from other batches. The food was decent too — pizza could've been hotter, but the games were a hit.",
    createdAt: daysFromNow(-11, 21),
  },
];
